"use client";

import styles from './ImageGenerationCard.module.css';

interface ImageGenerationCardProps {
  modelName: string;
  imageUrl: string;
  providerIcon?: string; // Optional: path to provider's icon
  onDownload: () => void;
  onCopy: () => void;
  onRegenerate: () => void;
}

export default function ImageGenerationCard({
  modelName,
  imageUrl,
  providerIcon,
  onDownload,
  onCopy,
  onRegenerate,
}: ImageGenerationCardProps) {
  return (
    <div className={styles.card}>
      <div className={styles.header}>
        {providerIcon && <img src={providerIcon} alt="" className={styles.providerIcon} />}
        <span className={styles.modelName}>{modelName}</span>
      </div>
      <div className={styles.imageContainer}>
        <img src={imageUrl} alt={`Generated by ${modelName}`} className={styles.image} />
      </div>
      <div className={styles.actions}>
        <button onClick={onDownload} className={styles.actionButton}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>
          Download
        </button>
        <button onClick={onCopy} className={styles.actionButton}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
          Copy
        </button>
      </div>
      <button onClick={onRegenerate} className={styles.regenerateButton}>
        Regenerate
      </button>
    </div>
  );
} 